services:
  db:
    container_name: CrickPredictionDB 
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME} 
    ports:
      - "${DB_PORT:-5431}:5432" 
    volumes:
      - mypg-data:/var/lib/postgresql/data

volumes:
  mypg-data: {}
