services:
  db:
    container_name: CrickPredictionDB
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT:-5431}:5432"
    volumes:
      - mypg-data:/var/lib/postgresql/data

  redis:
    container_name: CrickPredictionRedis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
    command: ["redis-server", "--appendonly", "yes"] # Enables data persistence

volumes:
  mypg-data: {}
  redis-data: {}
